- name: "Install 'sysutils/py-psutil' package, for ansible dconf support"
  # See https://docs.ansible.com/ansible/latest/collections/community/general/dconf_module.html#notes
  ansible.builtin.package:
    name: sysutils/py-psutil
    state: latest
  become: true
  become_user: root

- name: "Ensure dbus service is started, and set to start at boot"
  # See https://docs.freebsd.org/en/books/handbook/x11/#x11-wm
  ansible.builtin.service:
    name: dbus
    state: started
    enabled: yes
  become: true
  become_user: root

- name: "Mount procfs, and set it to mount at boot in /etc/fstab"
  # See https://docs.freebsd.org/en/books/handbook/x11/#x11-wm
  ansible.posix.mount:
    src: 'proc'
    path: '/proc'
    fstype: 'procfs'
    opts: 'rw'
    dump: '0'
    passno: '0'
    state: mounted
  become: true
  become_user: root

