# See https://docs.ansible.com/ansible/latest/collections/community/general/dconf_module.html#notes
- name: "Install 'python-psutil' package, for ansible dconf support"
  community.general.pacman:
    name: python-psutil
    state: present
  become: true
  become_user: root

