- name: "Install '{{ pkg_name }}' package, for default button/action sounds"
  ansible.builtin.package:
    name: "{{ pkg_name }}"
    state: present
  vars:
    pkg_name: 'freedesktop-sound-theme'
  become: true
  become_user: root
  when: enable_sound_support

