- name: "Write an empty list to a dconf setting, and try again if it fails"
  block:
    - name: "{{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        # value: "{{ empty_list | string }}"
        state: absent
  rescue:
    - name: "SECOND TRY - {{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        # value: "{{ empty_list | string }}"
        state: absent
  vars:
    empty_list: []
  become: true
  become_user: "{{ user_name }}"

