- name: "Write an empty list to a dconf setting, and try again if it fails"
  block:
    - name: "{{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        # value: "{{ empty_list | string }}"
        value: "@as []"
        state: present
  rescue:
    - name: "SECOND TRY - {{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        # value: "{{ empty_list | string }}"
        value: "@as []"
        state: present
  # vars:
  #   empty_list: ['Change Theme;mate-appearance-properties.desktop']
  become: true
  become_user: "{{ user_name }}"

