- name: "Write an empty list to a dconf setting, and try again if it fails"
  block:
    - name: "{{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        value: "{{ empty_list_value }}"
        state: present
  rescue:
    - name: "SECOND TRY - {{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        value: "{{ empty_list_value }}"
        state: present
  vars:
    empty_list_value: "@as []"
  become: true
  become_user: "{{ user_name }}"

