- name: "Remove a dconf setting, try again if it fails, and notify when changed"
  block:
    - name: "{{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        state: absent
      notify: "{{ notify_receiver }}"
  rescue:
    - name: "SECOND TRY - {{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        state: absent
      notify: "{{ notify_receiver }}"
  become: true
  become_user: "{{ user_name }}"

