- name: "Edit a dconf setting, try again if it fails, and force value to string"
  block:
    - name: "{{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        value: "{{ value | string }}"
        state: present
  rescue:
    - name: "SECOND TRY - {{ descrip }}"
      community.general.dconf:
        key: "{{ key }}"
        value: "{{ value | string }}"
        state: present
  become: true
  become_user: "{{ user_name }}"

