- name: "Check if '{{ desktop_file_path }}' exists"
  ansible.builtin.stat:
    path: "{{ desktop_file_path }}"
  register: result
  become: true
  become_user: root

- name: "For '{{ desktop_file_basename }}.desktop', {{ short_descrip }}"
  ansible.builtin.lineinfile:
    path: "{{ desktop_file_path }}"
    regexp: "{{ line_regexp }}"
    line: "{{ line_replacement }}"
    insertafter: >-
      ^\[Desktop Entry\]$
    firstmatch: true
    state: present
    create: false
  become: true
  become_user: root
  when: result.stat.exists
  notify: restart-mate-panel

