- name: "Restart 'mate-panel' executable"
  ansible.builtin.command: pkill -a 'mate-panel'
  register: pk
  become: true
  become_user: root
  # NOTE: rc is 0 when proc is killed, and 1 when no proc found
  failed_when: pk.rc > 1

