- name: "Restart {{ panel_proc_name }}, if the process is running"
  block:
    - name: "Search for {{ panel_proc_name }} PID"
      community.general.pids:
        name: "{{ panel_proc_name }}"
      register: mate_panel_pids
    - name: "Restart {{ panel_proc_name }} executable"
      ansible.builtin.command: pkill '{{ panel_proc_name }}'
      when: (mate_panel_pids | length) > 0
  vars:
    panel_proc_name: "mate-panel"
  become: true
  become_user: root

