- name: "For Control Center, remove menu-file 'Internet and Network' menu"
  ansible.builtin.replace:
    path: "{{ matecc_path }}"
    regexp: >-
      ^\s\s<!-- Internet and Network(.|\n)+End Internet and Network -->\n$
  become: true
  become_user: root

- name: "For Control Center, remove menu-file 'Internet and Network' category"
  ansible.builtin.replace:
    path: "{{ matecc_path }}"
    regexp: >-
      ^\s*<Menuname>Internet and Network</Menuname>$
  become: true
  become_user: root

- name: "For Control Center, remove menu-file 'Hardware' menu"
  ansible.builtin.replace:
    path: "{{ matecc_path }}"
    regexp: >-
      ^\s\s<!-- Hardware(.|\n)+End Hardware -->\n$
  become: true
  become_user: root

- name: "For Control Center, remove menu-file 'Hardware' category"
  ansible.builtin.replace:
    path: "{{ matecc_path }}"
    regexp: >-
      ^\s*<Menuname>Hardware</Menuname>$
  become: true
  become_user: root

- name: "For Control Center, define unifying menu-file 'Administration' menu"
  ansible.builtin.replace:
    path: "{{ matecc_path }}"
    regexp: >-
      ^\s\s<!-- Administration(.|\n)+End Administration -->\n$
    replace: |-
      <!-- Administration category -->
      <Menu>
        <Name>Administration</Name>
        <Directory>mate-settings-system.directory</Directory>
        <Include>
          <And>
            <Category>Settings</Category>
            <Category>HardwareSettings</Category>
            <Not><Category>System</Category></Not>
          </And>
          <And>
            <Category>Printing</Category>
          </And>
        </Include>
      </Menu> <!-- End Administration -->
  become: true
  become_user: root

