- name: "Install and configure MATE system-layer packages and services for Arch Linux"
  ansible.builtin.include_tasks: archlinux/main.yml
  when: ansible_os_family == "Archlinux"

- name: "Install and configure MATE system-layer packages and services for FreeBSD"
  ansible.builtin.include_tasks: freebsd/main.yml
  when: ansible_os_family == "FreeBSD"

