- ansible.builtin.include_tasks: func/dconf_empty_list.yml
  vars:
    descrip: "For control center, remove the 'Common Tasks' section in sidebar"
    key: "/org/mate/control-center/cc-actions-list"

- name: "For control center, remove menu file 'Internet and Network' menu"
  ansible.builtin.replace:
    path: /etc/xdg/menus/matecc.menu
    regexp: >-
      ^\s\s<!-- Internet and Network(.|\n)+End Internet and Network -->\n\n$
    replace: ''
  become: true
  become_user: root

