- ansible.builtin.include_tasks: func/dconf_empty_list.yml
  vars:
    descrip: "For control center, remove the 'Common Tasks' section in sidebar"
    key: "/org/mate/control-center/cc-actions-list"

