- ansible.builtin.include_tasks: func/dconf_empty_list.yml
  vars:
    descrip: "For control center, remove the 'Common Tasks' section in sidebar"
    key: "/org/mate/control-center/cc-actions-list"

- name: "Change Control Center app appearance by editing {{ matecc_path }}"
  block:
    - name: "For control center, remove menu-file 'Internet and Network' menu"
      ansible.builtin.replace:
        path: "{{ matecc_path }}"
        regexp: >-
          ^\s\s<!-- Internet and Network(.|\n)+End Internet and Network -->\n$
    - name: "For control center, remove menu-file 'Internet and Network' category"
      ansible.builtin.replace:
        path: "{{ matecc_path }}"
        regexp: >-
          ^\s*<Menuname>Internet and Network</Menuname>$
    - name: "For control center, remove menu-file 'Hardware' menu"
      ansible.builtin.replace:
        path: "{{ matecc_path }}"
        regexp: >-
          ^\s\s<!-- Hardware(.|\n)+End Hardware -->\n$
    - name: "For control center, remove menu-file 'Hardware' category"
      ansible.builtin.replace:
        path: "{{ matecc_path }}"
        regexp: >-
          ^\s*<Menuname>Hardware</Menuname>$
    - name: "For control center, define unifying menu-file 'Administration' menu"
      ansible.builtin.replace:
        path: "{{ matecc_path }}"
        regexp: >-
          ^\s\s<!-- Administration(.|\n)+End Administration -->\n$
        replace: |-
          <!-- Administration category -->
          <Menu>
            <Name>Administration</Name>
            <Directory>mate-settings-system.directory</Directory>
            <Include>
              <And>
                <Category>Settings</Category>
                <Category>HardwareSettings</Category>
                <Not><Category>System</Category></Not>
              </And>
              <And>
                <Category>Printing</Category>
              </And>
            </Include>
          </Menu> <!-- End Administration -->
  vars:
    matecc_path: '/etc/xdg/menus/matecc.menu'
  become: true
  become_user: root

