- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For interface behavior, set cursor-blink to '{{ blink_on }}'"
    key: "/org/mate/desktop/interface/cursor-blink"
    value: "{{ blink_on }}"
    blink_on: "{{ 'false' if (interface_cursor_blink_time == '0') else 'true' }}"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For interface behavior, set cursor-blink-time to {{ interface_cursor_blink_time }} millisec"
    key: "/org/mate/desktop/interface/cursor-blink-time"
    value: "{{ interface_cursor_blink_time }}"
  when: interface_cursor_blink_time != '0'

