- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set enable-keypress-repeat to '{{ repeat_on }}'"
    key: "/org/mate/desktop/peripherals/keyboard/repeat"
    value: "{{ repeat_on }}"
    repeat_on: "{{ 'false' if (keyboard_repeat_rate == 'none') else 'true' }}"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set keypress-repeat-rate to {{ keyboard_repeat_rate }} millisec"
    key: "/org/mate/desktop/peripherals/keyboard/rate"
    value: "{{ keyboard_repeat_rate }}"
  when: keyboard_repeat_delay != 'none'

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set keypress-repeat-delay to {{ keyboard_repeat_delay }} millisec"
    key: "/org/mate/desktop/peripherals/keyboard/delay"
    value: "{{ keyboard_repeat_delay }}"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For keyboard, set enable-audible-bell to '{{ bell_on }}'"
    key: "/org/mate/desktop/peripherals/keyboard/bell-mode"
    value: "'{{ bell_on }}'"
    bell_on: "{{ 'on' if keyboard_bell_enable else 'off' }}"

