- name: "In WM, hide 'computer' desktop icons"
  community.general.dconf:
    key: "/org/mate/caja/desktop/computer-icon-visible"
    value: "true"
    state: present
  become: true
  become_user: "{{ user_name }}"

- name: "Configure MATE Terminal settings"
  ansible.builtin.include_tasks: mate_terminal.yml

