- name: "In MATE Terminal app, set background to '{{ terminal_bg_type }}'"
  community.general.dconf:
    key: "/org/mate/terminal/profiles/default/background-type"
    value: "transparent"
    state: present
  become: true
  become_user: "{{ user_name }}"

- name: "In MATE Terminal app, set background transparency to {{ terminal_bg_transparency }}"
  community.general.dconf:
    key: "/org/mate/terminal/profiles/default/background-darkness"
    value: "{{ terminal_bg_transparency }}"
    state: present
  become: true
  become_user: "{{ user_name }}"
  when: terminal_bg_type == 'transparent'

