- name: "Configure MATE Terminal app settings"
  block:
    - name: "In MATE Terminal app, set background to '{{ bg_type }}'"
      community.general.dconf:
        key: "/org/mate/terminal/profiles/default/background-type"
        value: "'{{ bg_type }}'"
        state: present
      vars:
        bg_type: "{{ 'solid' if (terminal_bg_transparency == '1.00') else 'transparent' }}"
    - name: "In MATE Terminal app, set background transparency to {{ terminal_bg_transparency }}"
      community.general.dconf:
        key: "/org/mate/terminal/profiles/default/background-darkness"
        value: "{{ terminal_bg_transparency }}"
        state: present
      when: terminal_bg_transparency != '1.00'
      changed_when: false
    - name: "In MATE Terminal app, set background color to '{{ terminal_bg_color }}'"
      community.general.dconf:
        key: "/org/mate/terminal/profiles/default/background-color"
        value: "'{{ terminal_bg_color }}'"
        state: present
    - name: "In MATE Terminal app, set foreground/text color to '{{ terminal_fg_color }}'"
      community.general.dconf:
        key: "/org/mate/terminal/profiles/default/foreground-color"
        value: "'{{ terminal_fg_color }}'"
        state: present
  become: true
  become_user: "{{ user_name }}"

