- name: "Hide select entries from appearing in 'Applications' menu"
  ansible.builtin.include_tasks: func/desktop_entry_hide.yml
  vars:
    desktop_file_basename: "{{ item }}"
  loop:
    - "avahi-discover"
    - "bssh"
    - "bvnc"
    - "caja-browser"
    - "cups"
    - "engrampa"
    - "eom"
    - "libreoffice-base"
    - "mate-color-select"
    - "mate-dictionary"
    - "mate-disk-image-mounter"
    - "mate-font-viewer"
    - "mate-power-statistics"
    - "mate-system-log"
    - "mate-volume-control"
    - "org.fontforge.FontForge"
    - "qv4l2"
    - "qvidcap"
    - "vim"

- name: "Set submenu category for select 'Applications' menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_category.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    category: "{{ item.cat }}"
  loop:
    - { basename: 'libreoffice-draw', cat: 'Graphics' }
    - { basename: 'libreoffice-math', cat: 'Office' }
    - { basename: 'mate-search-tool', cat: 'Core' }
    - { basename: 'pluma', cat: 'Office' }

- name: "Set item title for select 'Applications' menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_title.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    title: "{{ item.title }}"
  loop:
    - { basename: 'libreoffice-startcenter', title: 'LibreOffice Start Page' }
    - { basename: 'pluma', title: 'Pluma Text Editor' }
    - { basename: 'atril', title: 'Atril PDF Document Viewer' }
    - { basename: 'vlc', title: 'VLC Video Player' }

- name: "Set mouse-hover tooltip for select 'Applications' menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_tooltip.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    tooltip: "{{ item.tooltip }}"
  loop:
    - { basename: 'atril', tooltip: 'View multi-page PDF documents' }
    - { basename: 'libreoffice-startcenter', tooltip: 'Open recent LibreOffice docs, or create new ones' }
    - { basename: 'vlc', tooltip: 'Play video/audio files and DVDs' }

