- name: "Hide select entries from appearing in 'Applications' menu"
  ansible.builtin.include_tasks: func/desktop_entry_hide.yml
  vars:
    desktop_file_basename: "{{ item }}"
  loop:
    - "engrampa"
    - "vim"
    - "mate-font-viewer"
    - "eom"
    - "mate-color-select"
    - "bssh"
    - "bvnc"
    - "avahi-discover"
    - "mate-dictionary"
    - "mate-volume-control"
    - "caja-browser"
    - "mate-system-log"
    - "mate-disk-image-mounter"
    - "mate-power-statistics"

- name: "Set submenu category for select 'Applications' menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_category.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    category: "{{ item.cat }}"
  loop:
    - { basename: 'pluma', cat: 'Office' }
    - { basename: 'mate-search-tool', cat: 'Core' }

- name: "Set item title for select 'Applications' menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_title.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    title: "{{ item.title }}"
  loop:
    - { basename: 'pluma', title: 'Pluma Text Editor' }
    - { basename: 'atril', title: 'Atril PDF Document Viewer' }

- name: "Set mouse-hover tooltip for select 'Applications' menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_tooltip.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    tooltip: "{{ item.tooltip }}"
  loop:
    - { basename: 'atril', tooltip: 'View multi-page PDF documents' }

