- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For menu, set show-icon to '{{ show_icon }}'"
    key: "/org/mate/panel/menubar/show-icon"
    value: "{{ show_icon }}"
    show_icon: "{{ 'true' if menu_show_icon else 'false' }}"

