- name: "Hide select entries from appearing in 'Applications' menu"
  ansible.builtin.include_tasks: func/hide_desktop_entry.yml
  vars:
    desktop_file_basename: "{{ item }}"
  loop:
    - "engrampa"
    - "vim"
    - "mate-font-viewer"
    - "eom"
    - "mate-color-select"
    - "bssh"
    - "bvnc"
    - "avahi-discover"
    - "mate-dictionary"
    - "mate-volume-control"
    - "caja-browser"
    - "mate-system-log"
    - "mate-disk-image-mounter"
    - "mate-power-statistics"

