- name: "Hide select entries from appearing in 'Applications' menu"
  ansible.builtin.include_tasks: func/hide_desktop_entry.yml
  vars:
    desktop_file_basename: "{{ item }}"
  loop:
    - "engrampa"
    - "vim"
    - "mate-font-viewer"
    - "eom"
    - "mate-color-select"
    - "bssh"
    - "bvnc"
    - "avahi-discover"
    - "mate-dictionary"
    - "mate-volume-control"
    - "caja-browser"
    - "mate-system-log"
    - "mate-disk-image-mounter"
    - "mate-power-statistics"

- name: "Set submenu category for select 'Applications' menu entries"
  ansible.builtin.include_tasks: func/set_desktop_entry_cat.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    category: "{{ item.cat }}"
  loop:
    - { basename: 'pluma', cat: 'Office' }
    - { basename: 'mate-search-tool', cat: 'Core' }
    - { basename: 'mate-disk-usage-analyzer', cat: 'Utility' }
    - { basename: 'mate-system-monitor', cat: 'Utility' }
    - { basename: 'mate-terminal', cat: 'Utility' }

