- name: "Configure general panel settings"
  block:
    - name: "For panels, set available items for all panels to {{ panels_available_items }}"
      community.general.dconf:
        key: "/org/mate/panel/general/object-id-list"
        value: "{{ panels_available_items | string }}"
        state: present
  become: true
  become_user: "{{ user_name }}"

- name: "Configure top panel settings"
  block:
    - name: "For top panel, set panel-size to {{ size }}"
      community.general.dconf:
        key: "/org/mate/panel/toplevels/top/size"
        value: "{{ size }}"
        state: present
      vars:
        size: "{{ top_panel_size }}"
    - name: "For top panel, set background-type to '{{ bg_type }}'"
      community.general.dconf:
        key: "/org/mate/panel/toplevels/top/background/type"
        value: "'{{ bg_type }}'"
        state: present
      vars:
        bg_type: "color"
    - name: "For top panel, set background-color to '{{ panels_background_color }}'"
      community.general.dconf:
        key: "/org/mate/panel/toplevels/top/background/color"
        value: "'{{ panels_background_color }}'"
        state: present
  become: true
  become_user: "{{ user_name }}"

- name: "Configure bottom panel settings"
  block:
    - name: "For bottom panel, set panel-size to {{ size }}"
      community.general.dconf:
        key: "/org/mate/panel/toplevels/bottom/size"
        value: "{{ size }}"
        state: present
      vars:
        size: "{{ bottom_panel_size }}"
    - name: "For bottom panel, set background-type to '{{ bg_type }}'"
      community.general.dconf:
        key: "/org/mate/panel/toplevels/bottom/background/type"
        value: "'{{ bg_type }}'"
        state: present
      vars:
        bg_type: "color"
    - name: "For bottom panel, set background-color to '{{ panels_background_color }}'"
      community.general.dconf:
        key: "/org/mate/panel/toplevels/bottom/background/color"
        value: "'{{ panels_background_color }}'"
        state: present
  become: true
  become_user: "{{ user_name }}"

