- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For windowing actions, set draw-animations to '{{ use_animations }}'"
    key: "/org/mate/desktop/interface/enable-animations"
    value: "{{ use_animations }}"
    use_animations: "{{ 'true' if windowing_animations else 'false' }}"

- ansible.builtin.include_tasks: func/dconf.yml
  vars:
    descrip: "For windowing, set num-workspaces to {{ num_wkspc }}"
    key: "/org/mate/marco/general/num-workspaces"
    value: "{{ num_wkspc }}"
    num_wkspc: "{{ windowing_num_workspaces }}"

