- name: "Install MATE Control Center packages"
  block:
    - name: "Install 'mate-power-manager' package"
      community.general.pacman:
        name: mate-power-manager
        state: present
    - name: "Install 'network-manager-applet' package"
      community.general.pacman:
        name: network-manager-applet
        state: present
    - name: "Install 'mate-media' package, for sound support"
      community.general.pacman:
        name: mate-media
        state: present
      when: enable_sound_support
    - name: "Install 'libcanberra' package, for speaker-test sounds"
      community.general.pacman:
        name: libcanberra
        state: present
        extra_args: "--asdeps"
      when: enable_sound_support
    - name: "Install 'system-config-printer' package, for printing support"
      community.general.pacman:
        name: system-config-printer
        state: present
      when: enable_printing_support
  become: true
  become_user: root

