- name: "Install 'xorg-server' display server package"
  community.general.pacman:
    name: xorg-server
    state: present
  become: true
  become_user: root

- name: "Remove 'mate-user-guide' package (part of 'mate' package-group)"
  community.general.pacman:
    name: mate-user-guide
    state: removed
    extra_args: --recursive --nosave
  become: true
  become_user: root

