- name: "Install 'xorg-server' display server package"
  community.general.pacman:
    name: xorg-server
    state: present
  become: true
  become_user: root

- name: "Install base 'mate' package-group"
  community.general.pacman:
    name: mate
    state: present
    extra_args: --needed
  become: true
  become_user: root

