- name: "Install MATE-supported packages from 'mate-extra' package group"
  block:
    - name: "Install 'mate-utils' package, for screenshots/disk-usage/etc"
      community.general.pacman:
        name: mate-utils
        state: present
    - name: "Install 'caja-wallpaper' package, for caja set-wallpaper shortcut"
      community.general.pacman:
        name: caja-wallpaper
        state: present
    - name: "Install 'mate-screensaver' package"
      community.general.pacman:
        name: mate-screensaver
        state: present
    - name: "Install 'mate-system-monitor' package"
      community.general.pacman:
        name: mate-system-monitor
        state: present
    - name: "Install 'engrampa' package, for archive support"
      community.general.pacman:
        name: engrampa
        state: present
    - name: "Install 'mate-calc' package, for a desktop calculator app"
      community.general.pacman:
        name: mate-calc
        state: present
    - name: "Install 'eom' (eye-of-MATE) package, for a desktop image-viewer app"
      community.general.pacman:
        name: eom
        state: present
    - name: "Install 'atril' package, for a pdf-viewer app"
      community.general.pacman:
        name: atril
        state: present
    - name: "Install 'pluma' package, for a text-editor app"
      community.general.pacman:
        name: pluma
        state: present
    - name: "Install 'mate-terminal' package, for a terminal emulator app"
      community.general.pacman:
        name: mate-terminal
        state: present
  become: true
  become_user: root

