- name: "MATE: install base 'mate' and 'mate-extra' packages"
  ansible.builtin.include_tasks: install_base_pkgs.yml

- name: "MATE: install Control Center packages"
  ansible.builtin.include_tasks: install_ctl_ctr_pkgs.yml

