# See https://docs.ansible.com/ansible/latest/collections/community/general/dconf_module.html#notes
- name: "Install 'sysutils/py-psutil' package, for ansible dconf support"
  ansible.builtin.package:
    name: sysutils/py-psutil
    state: present
  become: true
  become_user: root

# - name: "Install 'xdg-utils' package, for .desktop file support"
#   ansible.builtin.package:
#     name: xdg-utils
#     state: present
#   become: true
#   become_user: root

