- name: "Install '{{ item.pkgname }}' package, for {{ item.descrip }}"
  ansible.builtin.package:
    name: "{{ item.pkgname }}"
    state: present
  loop:
    - { pkgname: 'mate-utils', descrip: 'screenshots/disk-usage/etc' }
    - { pkgname: 'mate-screensaver', descrip: 'basic screensavers' }
    - { pkgname: 'mate-system-monitor', descrip: 'a process/memory monitor app' }
    - { pkgname: 'engrampa', descrip: 'archive support' }
    - { pkgname: 'mate-calc', descrip: 'a desktop calculator app' }
    - { pkgname: 'eom', descrip: 'a desktop image-viewer app' }
    - { pkgname: 'atril', descrip: 'a pdf-viewer app' }
    - { pkgname: 'pluma', descrip: 'a text-editor app' }
    - { pkgname: 'mate-terminal', descrip: 'a terminal emulator app' }

