- name: "Install mate-specific application packages"
  ansible.builtin.package:
    name: "{{ item.pkg }}"
    state: present
  loop:
    - { pkg: 'mate-utils', descrip: 'screenshots/disk-usage/etc' }
    - { pkg: 'mate-screensaver', descrip: 'basic screensavers' }
    - { pkg: 'mate-system-monitor', descrip: 'a process/memory monitor app' }
    - { pkg: 'engrampa', descrip: 'archive support' }
    - { pkg: 'mate-calc', descrip: 'a desktop calculator app' }
    - { pkg: 'eom', descrip: 'a desktop image-viewer app' }
    - { pkg: 'atril', descrip: 'a pdf-viewer app' }
    - { pkg: 'pluma', descrip: 'a text-editor app' }
    - { pkg: 'mate-terminal', descrip: 'a terminal emulator app' }

