- name: "Hide select entries from appearing in 'Applications' start menu"
  ansible.builtin.include_tasks: func/desktop_entry_hide.yml
  vars:
    desktop_file_basename: "{{ item }}"
  loop:
    - 'avahi-discover'
    - 'bssh'
    - 'bvnc'
    - 'caja-browser'
    - 'cups'
    - 'engrampa'
    - 'eom'
    - 'fish'
    - 'libreoffice-base'
    - 'mate-color-select'
    - 'mate-dictionary'
    - 'mate-disk-image-mounter'
    - 'mate-font-viewer'
    - 'mate-power-statistics'
    - 'mate-system-log'
    - 'org.fontforge.FontForge'
    - 'org.gnome.Glade'
    - 'org.gtk.Demo4'
    - 'org.gtk.IconBrowser4'
    - 'org.gtk.PrintEditor4'
    - 'org.gtk.WidgetFactory4'
    - 'org.gtk.gtk4.NodeEditor'
    - 'qv4l2'
    - 'qvidcap'
    - 'vim'
    - 'ca.desrt.dconf-editor'

- name: "For FreeBSD, hide MATE sound-prefs-app, since GTK-mixer replaces it"
  ansible.builtin.include_tasks: func/desktop_entry_hide.yml
  vars:
    desktop_file_basename: 'mate-volume-control'
  when: ansible_os_family == "FreeBSD"

- name: "Set icon for select 'Applications' start menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_icon.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    icon: "{{ item.ic }}"
  loop:
    - { basename: 'gtkmixer', ic: 'multimedia-volume-control' }

- name: "Set submenu category for select 'Applications' start menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_category.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    category: "{{ item.cat }}"
  loop:
    - { basename: 'gtkmixer', cat: 'Mixer;Settings;HardwareSettings' }
    - { basename: 'libreoffice-draw', cat: 'Graphics' }
    - { basename: 'libreoffice-math', cat: 'Office' }
    - { basename: 'mate-search-tool', cat: 'Core' }
    - { basename: 'mate-volume-control', cat: 'Settings;HardwareSettings' }
    - { basename: 'pluma', cat: 'Office' }

- name: "Set item title for select 'Applications' start menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_title.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    title: "{{ item.title }}"
  loop:
    - { basename: 'atril', title: 'Atril PDF Document Viewer' }
    - { basename: 'com.obsproject.Studio', title: 'OBS Video Recording' }
    - { basename: 'chromium-browser', title: 'Chromium (Backup & Video-Conference Browser)' }
    - { basename: 'firefox', title: 'Firefox (Main Browser)' }
    - { basename: 'gtkmixer', title: 'Sound' }
    - { basename: 'libreoffice-startcenter', title: 'LibreOffice Start Page' }
    - { basename: 'net.sourceforge.gscan2pdf', title: 'gscan2pdf Document Scanner' }
    - { basename: 'org.gnome.Cheese', title: 'Cheese Webcam Snapshot' }
    - { basename: 'pluma', title: 'Pluma Text Editor' }
    - { basename: 'vlc', title: 'VLC Video Player' }

- name: "Set mouse-hover tooltip for select 'Applications' start menu entries"
  ansible.builtin.include_tasks: func/desktop_entry_tooltip.yml
  vars:
    desktop_file_basename: "{{ item.basename }}"
    tooltip: "{{ item.tooltip }}"
  loop:
    - { basename: 'atril', tooltip: 'View multi-page PDF documents' }
    - { basename: 'gtkmixer', tooltip: 'GTK sound device and volume control' }
    - { basename: 'libreoffice-startcenter', tooltip: 'Open recent LibreOffice docs, or create new ones' }
    - { basename: 'vlc', tooltip: 'Play video/audio files and DVDs' }

